### ISSUE TITLE
Default the editor theme to match the user's VS Code color theme

### ISSUE THREAD

**Issue by lostintangent** [zaaack/vscode-markdown-editor#1]
Hey! I love this extension, so thanks so much for creating it 😄 If possible, it would be amazing if you could default the editor theme to use the dark theme, if the user were using a dark theme in VS Code. It seems like this setting is persisted across VS Code sessions, and so the workaround is to simply manually change the theme once. But if I'm working across multiple machines, and syncing my VS Code theme across them, it would be cool to have the markdown editor reflect that. Thanks!

**Comment by zaaack** [comment]
@lostintangent Thanks for like this extension! The theme configuration should be automatically synchronized according to the vscode account. I'll try to set the default theme according to the vscode theme.

**Comment by zaaack** [comment]
Fixed in v0.0.6.
