### ISSUE TITLE
设置为 .md 文件的默认打开方式

### ISSUE THREAD

**Issue by ivaquero** [zaaack/vscode-markdown-editor#10]
这是个很棒的扩展，希望能添加设置，成为.md 文件的默认打开方式

**Comment by JerrallK** [comment]
+1 希望可以设置为默认编辑器

**Comment by faceair** [comment]
有计划实现吗？看起来思路可以参考 https://github.com/hnw/vscode-auto-open-markdown-preview/blob/master/src/extension.ts

**Comment by faceair** [comment]
效果不太好，[office viewer](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office
) 通过注册 CustomEditorProvider 实现的效果会更好一点，不过相对复杂一些
https://github.com/vscode-ext-studio/vscode-office/blob/master/src/extension.ts#L20

**Comment by fastfading** [comment]
这个优先级 调高吧，   不然用起来很不方便

**Comment by fastfading** [comment]
@faceair   期待你改进了， 不然用起来太麻烦 了。   我试用了所有类似软件，  就这个最好用了。

**Comment by fastfading** [comment]
vditor  自己本身就可以直接打开， 这个基于vditor 居然还不行

**Comment by jamesziwo** [comment]
这个插件是不是没人更新了.....

**Comment by xnervwang** [comment]
Why was this issue marked as completed? As a new user, this is the main reason that I want to uninstall this extension..
