### ISSUE TITLE
ONLINE CONNECTION MANDATORY: Editor not opening

### ISSUE THREAD

**Issue by digitalAssetStore** [zaaack/vscode-markdown-editor#12]
After installing the extension via *.vsix file the editor does not start.
(The editor stays just dark)

This happens on a computer that has no internet connection.
Is an internet connection mandatory? If so, why?

**Comment by zaaack** [comment]
@digitalAssetStore Yes, internet is necessary,  because some resource is loaded on CDN.

**Comment by digitalAssetStore** [comment]
How is the markdown file handled?

1. - Markdown file send to server?
2. - Markdown file only edited locally?

**Comment by zaaack** [comment]
They are edit locally, but vditor's some js/css are loaded dynamically on CDN, once you loaded, the static files are cached and no need internet next time.
