### ISSUE TITLE
一个奇怪的Bug

### ISSUE THREAD

**Issue by xmu714** [zaaack/vscode-markdown-editor#14]
我这里有一段带有公式的笔记，用Typora,vscode的MPE插件，还有放进思源笔记里面都可以正常解析，但是怎么在这个插件里面显示不正常：
```markdown
Test
这类极限主要包括三种未定型 $i^\infty, \  \infty^0, \  0^0$. 其中第一种是重点，后两种很少考察。

共同解法——指数化：$f(x)^{g(x)}=e^{g(x)\ln f(x)}$. 
这样可以将以上几种未定型全部转换为 $0 \cdot \infty$ 未定型，然后结合其他方法使用。

对于 $1^\infty$ 有特殊解法 $e^A$. 如果底数部分提供了1，那么可以简单计算。
```
插件里面解析是这样的：
![pic](https://xmu714-disk.oss-cn-shenzhen.aliyuncs.com/notepic/Screenshot_2021-05-18_21-39-10.png "显示效果")

可以看到，有三处没有将公式显示出来，最后一行居然跳过公式转而将中间的汉字当公式了。

我很疑惑，按说思源也是用的`Veditor`，可是在思源里面是可以正确显示的。我试过在插件的编辑器里重新手敲一边，当时看着都对了，然后重开又成了这样，很迷惑。

**Comment by zaaack** [comment]
@xmu714, 在 $ 和 0/1 之间加个空格貌似就可以解析了，我没动 vditor 的解析部分，可能是版本不同导致的吧。

```md
Test
这类极限主要包括三种未定型 $i^\infty, \  \infty^0, \  0^0$. 其中第一种是重点，后两种很少考察。

共同解法——指数化：$f(x)^{g(x)}=e^{g(x)\ln f(x)}$.
这样可以将以上几种未定型全部转换为 $ 0 \cdot \infty$ 未定型，然后结合其他方法使用。

对于 $ 1^\infty$ 有特殊解法 $e^A$. 如果底数部分提供了1，那么可以简单计算。

```

**Comment by zaaack** [comment]
在 vditor 的在线demo上也是如此：https://ld246.com/guide/markdown

**Comment by xmu714** [comment]
我试了下，还真是加上空格就可以了。不过思源里面是直接没问题的，这俩的编辑器居然版本不同？

**Comment by xmu714** [comment]
最新进展：已经在Veditor的项目里提了[issue](https://github.com/Vanessa219/vditor/issues/1007)，等开发跟进。
目前我是在数字前面填充了一个小空格`$\,`来保证我复制到博客里面不影响解析，好像mathjax严格要求行内公式不能$+空格。
这个后续可能他们会给一个可配置的接口，你可以做到插件选项里面去。

**Comment by zaaack** [comment]
fixed in v0.1.6
