### ISSUE TITLE
Cannot open link to relative path. AND how to open link with markdown editor

### ISSUE THREAD

**Issue by NikoKS** [zaaack/vscode-markdown-editor#17]
Thank you for fixing the broken link issue with version 0.1.8.

But there are still some problem/feature request with links.

1. Opening link to a relative file path doesn't seem to be working. For example, when creating the link `[test](test.md)`, clicking the link would cause a pop up to show:
<img width="444" alt="Screen Shot 2021-06-05 at 10 07 07 AM" src="https://user-images.githubusercontent.com/24285511/120899848-8a65a800-c5e6-11eb-8467-98f918fcd173.png">

2. Can you make it so that if a link to a markdown file is opened, it would default to open it using the markdown editor? This would be very useful for linking different markdown notes.

**Comment by zaaack** [comment]
fixed in v0.1.9

**Comment by NikoKS** [comment]
Thank You, Link to local files works now!

Is there an option to open the link using markdown editor by default?
