### ISSUE TITLE
What's the difference from the UNOTES?

### ISSUE THREAD

**Issue by Sean10** [zaaack/vscode-markdown-editor#18]
Sorry for this question, but i'd really like to get the difference as a user except for the different infrastructure. 

[ryanmcalister/unotes: Unotes Visual Studio Code Extension\. A markdown WYSIWYG notes editor\.](https://github.com/ryanmcalister/unotes)

And i found another extension [tejasvi/markless: WIP right now](https://github.com/tejasvi/markless) which satisfy all my need, looks like a  intergreted vscode markdown renderer which still could use most of my other extensions' keybinds. Without changing my typing habits, I could immediately enjoy it.

**Comment by zaaack** [comment]
Well, vscode-markdown-editor has many differences compare to unotes, I didn't use unotes before, but I think we can have different implementation or features for more choice.
