### ISSUE TITLE
Is there some ways  to set relative path for saving images pasted  to markdown

### ISSUE THREAD

**Issue by Sologala** [zaaack/vscode-markdown-editor#19]
It is nice that `vscode-markdown-editor` extension is able to insert images. but, in my own custom habits, I'd like to save images to `./{markdown_file_name}/***.jpg`. So , Is there some marcos to indicates the filename or current folders ? like `${file} `or `${fileName}`

**Comment by zaaack** [comment]
fixed in v0.1.10
