### ISSUE TITLE
No outline displayed

### ISSUE THREAD

**Issue by huntertran** [zaaack/vscode-markdown-editor#5]
![image](https://user-images.githubusercontent.com/4468525/116335104-463fe600-a7a4-11eb-914b-65822ed8331d.png)

The normal .md file has a nice outline displayed. It would be great if this extension could support that feature

**Comment by zaaack** [comment]
![image](https://user-images.githubusercontent.com/5233940/116344941-bb013780-a819-11eb-8a06-637e929e8167.png)

You can use the built-in outline currently.

**Comment by dougbreaux** [comment]
Is this gone? I have no such option
