### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by evgnz** [zaaack/vscode-markdown-editor#6]
Popups menu items overlapped with a tooltip, maybe just shift them to the top or to the right. 
Screenshots: https://i.imgur.com/jmQw1PF.png https://i.imgur.com/LBIMLp8.png
Thanks.

**Comment by zaaack** [comment]
fixed in v0.1.5(https://github.com/zaaack/vscode-markdown-editor/commit/a1c39b35b4fd424be94c9b551a143c0b7b4c4574)

**Comment by evgnz** [comment]
Thank you.
