### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by FelixLangot** [zaaack/vscode-markdown-editor#8]
Hi, I really like this extension which has been super useful to me. I was wondering if we could get the option to choose the language used by the extension ? More precisely when I make a table and I click on the table options for example, the options are explained in Chinese which I don't understand. Thanks for the extension anyway, works really well!!

**Comment by zaaack** [comment]
fixed in v0.1.5(https://github.com/zaaack/vscode-markdown-editor/commit/a1c39b35b4fd424be94c9b551a143c0b7b4c4574)
